create table Employee (
	employee_id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	phone VARCHAR(50),
	role VARCHAR(18),
	location_id VARCHAR(50)
);
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (1, 'Danna', 'Pointon', 'dpointon0@scribd.com', '526-689-0922', 'Maintenance Staff', '54');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (2, 'Heidi', 'Marritt', 'hmarritt1@shutterfly.com', '667-309-4316', 'Branch Manager', '80');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (3, 'Keven', 'Ganley', 'kganley2@google.ca', '216-731-4749', 'Administrator', '23');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (4, 'Kippy', 'Simonin', 'ksimonin3@engadget.com', '636-969-7230', 'Quality Control', '67');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (5, 'Modesta', 'Akers', 'makers4@nasa.gov', '287-360-8060', 'Administrator', '71');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (6, 'Arlee', 'Gianullo', 'agianullo5@google.com.au', '380-500-8458', 'Maintenance Staff', '7');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (7, 'Chiquita', 'Punchard', 'cpunchard6@tuttocitta.it', '650-792-3428', 'Rental Clark/Agent', '100');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (8, 'Myca', 'Dionsetti', 'mdionsetti7@soup.io', '878-351-1758', 'Quality Control', '79');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (9, 'Leisha', 'Fallow', 'lfallow8@reddit.com', '219-289-5955', 'Quality Control', '31');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (10, 'Hugibert', 'Hernik', 'hhernik9@ebay.com', '491-976-7778', 'Branch Manager', '69');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (11, 'Chico', 'Abreheart', 'cabrehearta@vistaprint.com', '954-251-8068', 'Branch Manager', '46');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (12, 'Kayne', 'Stanlick', 'kstanlickb@buzzfeed.com', '462-207-6919', 'Fleet Manager', '72');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (13, 'Jonell', 'Road', 'jroadc@printfriendly.com', '135-169-4342', 'Branch Manager', '16');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (14, 'Ingrid', 'Yakuntsov', 'iyakuntsovd@nyu.edu', '454-745-6182', 'Administrator', '65');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (15, 'Alvy', 'Rillett', 'arillette@fema.gov', '688-637-0794', 'Rental Clark/Agent', '29');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (16, 'Hilton', 'Lathe', 'hlathef@state.tx.us', '507-876-9618', 'Administrator', '12');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (17, 'Angie', 'McGourty', 'amcgourtyg@51.la', '841-125-9525', 'Rental Clark/Agent', '63');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (18, 'Kaleb', 'di Rocca', 'kdiroccah@businessweek.com', '887-162-6684', 'Administrator', '74');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (19, 'Kimball', 'Dilleston', 'kdillestoni@fema.gov', '340-973-4841', 'Branch Manager', '87');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (20, 'Dorice', 'Matskevich', 'dmatskevichj@wunderground.com', '865-639-5508', 'Rental Clark/Agent', '86');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (21, 'Ginni', 'Puxley', 'gpuxleyk@rambler.ru', '540-234-8318', 'Quality Control', '44');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (22, 'Wilbert', 'Uzelli', 'wuzellil@blinklist.com', '116-881-7032', 'Administrator', '47');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (23, 'Indira', 'Gourdon', 'igourdonm@de.vu', '315-263-3762', 'Maintenance Staff', '76');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (24, 'Louise', 'Merrison', 'lmerrisonn@yahoo.co.jp', '807-760-4267', 'Quality Control', '83');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (25, 'Ricky', 'O''Scollee', 'roscolleeo@opensource.org', '742-214-3566', 'Branch Manager', '70');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (26, 'Dannel', 'Autie', 'dautiep@buzzfeed.com', '770-960-8145', 'Administrator', '93');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (27, 'Terrel', 'Ellison', 'tellisonq@cbsnews.com', '410-354-9321', 'Maintenance Staff', '99');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (28, 'Monte', 'Spurden', 'mspurdenr@army.mil', '451-898-2580', 'Quality Control', '25');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (29, 'Melita', 'Puddle', 'mpuddles@etsy.com', '739-434-0097', 'Branch Manager', '57');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (30, 'Theressa', 'Yantsurev', 'tyantsurevt@printfriendly.com', '745-269-4153', 'Quality Control', '77');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (31, 'Anne-marie', 'Anmore', 'aanmoreu@naver.com', '964-942-8566', 'Rental Clark/Agent', '27');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (32, 'Lila', 'Lammert', 'llammertv@reuters.com', '675-316-4703', 'Fleet Manager', '34');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (33, 'Amerigo', 'Hammer', 'ahammerw@about.me', '918-800-3529', 'Maintenance Staff', '66');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (34, 'Britta', 'Akaster', 'bakasterx@oakley.com', '887-717-4416', 'Rental Clark/Agent', '24');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (35, 'Catherin', 'Dourin', 'cdouriny@icq.com', '909-330-6835', 'Quality Control', '3');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (36, 'Jerrie', 'Libri', 'jlibriz@w3.org', '507-338-8323', 'Administrator', '50');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (37, 'Lyn', 'Tocqueville', 'ltocqueville10@ning.com', '164-808-8516', 'Administrator', '43');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (38, 'Fianna', 'Woolfoot', 'fwoolfoot11@mozilla.org', '191-590-3526', 'Quality Control', '18');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (39, 'Leonidas', 'Hawken', 'lhawken12@discuz.net', '102-693-8716', 'Maintenance Staff', '36');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (40, 'Allister', 'Maynard', 'amaynard13@google.com', '929-508-0732', 'Fleet Manager', '2');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (41, 'Allin', 'Cawt', 'acawt14@ycombinator.com', '729-848-3401', 'Rental Clark/Agent', '14');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (42, 'Torrin', 'Pawden', 'tpawden15@meetup.com', '113-477-7349', 'Branch Manager', '38');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (43, 'Alayne', 'Lowres', 'alowres16@msn.com', '169-235-4515', 'Administrator', '42');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (44, 'Dulce', 'Leatt', 'dleatt17@ed.gov', '402-534-1427', 'Rental Clark/Agent', '11');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (45, 'Olympia', 'Ferreli', 'oferreli18@gizmodo.com', '826-657-9060', 'Administrator', '59');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (46, 'Noelle', 'Rupel', 'nrupel19@google.es', '430-760-4090', 'Rental Clark/Agent', '52');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (47, 'Erek', 'Golbourn', 'egolbourn1a@house.gov', '921-765-9183', 'Branch Manager', '64');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (48, 'Daphene', 'Dunklee', 'ddunklee1b@unblog.fr', '421-769-8354', 'Administrator', '37');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (49, 'Hyacinthe', 'Mougin', 'hmougin1c@plala.or.jp', '373-752-9894', 'Quality Control', '96');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (50, 'Evaleen', 'Knee', 'eknee1d@gravatar.com', '172-977-8212', 'Quality Control', '55');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (51, 'Mariska', 'Pinner', 'mpinner1e@angelfire.com', '472-626-0939', 'Maintenance Staff', '5');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (52, 'Vi', 'Blockley', 'vblockley1f@dagondesign.com', '469-545-6732', 'Quality Control', '75');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (53, 'Ashlee', 'Filyaev', 'afilyaev1g@cdc.gov', '802-939-3732', 'Branch Manager', '60');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (54, 'Loise', 'Hunnaball', 'lhunnaball1h@last.fm', '253-870-3124', 'Maintenance Staff', '19');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (55, 'Karel', 'Pipes', 'kpipes1i@economist.com', '428-336-2874', 'Branch Manager', '22');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (56, 'Maurise', 'Tonbridge', 'mtonbridge1j@edublogs.org', '872-499-4133', 'Rental Clark/Agent', '97');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (57, 'Alfy', 'Ubsdale', 'aubsdale1k@answers.com', '726-444-3979', 'Quality Control', '73');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (58, 'Ailis', 'McDermid', 'amcdermid1l@webs.com', '736-235-5705', 'Rental Clark/Agent', '94');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (59, 'Cybill', 'Handaside', 'chandaside1m@ebay.com', '940-943-4845', 'Administrator', '90');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (60, 'Ezekiel', 'Mackison', 'emackison1n@examiner.com', '565-355-3611', 'Quality Control', '35');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (61, 'Gal', 'Greenless', 'ggreenless1o@unesco.org', '874-943-3377', 'Quality Control', '58');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (62, 'Lambert', 'Glennon', 'lglennon1p@techcrunch.com', '104-391-2177', 'Administrator', '82');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (63, 'Bernadina', 'Threadgould', 'bthreadgould1q@aboutads.info', '145-460-0316', 'Fleet Manager', '49');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (64, 'Haze', 'Mothersole', 'hmothersole1r@stumbleupon.com', '716-437-6971', 'Rental Clark/Agent', '40');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (65, 'Elsbeth', 'Beceril', 'ebeceril1s@webeden.co.uk', '963-659-5220', 'Branch Manager', '8');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (66, 'Berkly', 'Thoumas', 'bthoumas1t@prweb.com', '940-690-9242', 'Maintenance Staff', '53');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (67, 'Morgun', 'Witchell', 'mwitchell1u@washington.edu', '479-653-5530', 'Quality Control', '85');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (68, 'Mattheus', 'Norridge', 'mnorridge1v@linkedin.com', '465-869-9637', 'Branch Manager', '61');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (69, 'Jacquette', 'Ert', 'jert1w@blog.com', '732-614-5271', 'Rental Clark/Agent', '15');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (70, 'Gus', 'Pree', 'gpree1x@yolasite.com', '915-334-8801', 'Quality Control', '30');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (71, 'Alicia', 'Hambribe', 'ahambribe1y@comcast.net', '652-219-6354', 'Quality Control', '9');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (72, 'Fons', 'Megarrell', 'fmegarrell1z@webs.com', '174-228-4512', 'Administrator', '41');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (73, 'Rianon', 'Mertgen', 'rmertgen20@yale.edu', '639-962-6281', 'Branch Manager', '1');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (74, 'Anica', 'Wordsworth', 'awordsworth21@imageshack.us', '537-166-2299', 'Maintenance Staff', '4');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (75, 'Cathlene', 'Reekie', 'creekie22@pinterest.com', '688-809-7009', 'Rental Clark/Agent', '92');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (76, 'Waldo', 'Pulster', 'wpulster23@harvard.edu', '999-365-0102', 'Maintenance Staff', '98');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (77, 'Ivy', 'Witz', 'iwitz24@google.com.br', '432-920-7909', 'Rental Clark/Agent', '33');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (78, 'Alberto', 'Vise', 'avise25@cnet.com', '558-931-8014', 'Fleet Manager', '20');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (79, 'Morgana', 'Scoggin', 'mscoggin26@t-online.de', '300-886-6873', 'Maintenance Staff', '26');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (80, 'Alexis', 'Worsley', 'aworsley27@networkadvertising.org', '740-514-8219', 'Quality Control', '13');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (81, 'Lee', 'Vasyunkin', 'lvasyunkin28@newsvine.com', '555-188-3851', 'Rental Clark/Agent', '39');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (82, 'Gabi', 'Pardie', 'gpardie29@uol.com.br', '291-421-2339', 'Fleet Manager', '10');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (83, 'Kennie', 'Augie', 'kaugie2a@amazon.com', '771-797-2004', 'Fleet Manager', '56');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (84, 'Mead', 'Marcroft', 'mmarcroft2b@sogou.com', '446-281-8153', 'Fleet Manager', '81');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (85, 'Aundrea', 'Gravener', 'agravener2c@usatoday.com', '238-766-2690', 'Branch Manager', '6');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (86, 'De', 'Javes', 'djaves2d@nationalgeographic.com', '702-236-7597', 'Quality Control', '84');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (87, 'Hermy', 'Rizzi', 'hrizzi2e@geocities.jp', '934-939-8746', 'Branch Manager', '88');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (88, 'Sioux', 'Wichard', 'swichard2f@bizjournals.com', '722-588-6722', 'Administrator', '68');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (89, 'Logan', 'Whether', 'lwhether2g@smugmug.com', '515-635-4767', 'Maintenance Staff', '21');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (90, 'Sherline', 'Manilo', 'smanilo2h@com.com', '697-960-5061', 'Maintenance Staff', '51');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (91, 'Martin', 'Gurery', 'mgurery2i@squidoo.com', '557-626-6778', 'Branch Manager', '89');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (92, 'Barbabra', 'De Mitris', 'bdemitris2j@mediafire.com', '444-630-9170', 'Quality Control', '45');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (93, 'Rhiamon', 'Moyes', 'rmoyes2k@yandex.ru', '654-118-4900', 'Administrator', '32');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (94, 'Conan', 'Gatty', 'cgatty2l@unesco.org', '507-881-8729', 'Branch Manager', '62');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (95, 'Veronique', 'Carolan', 'vcarolan2m@jigsy.com', '614-798-2103', 'Branch Manager', '95');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (96, 'Sigismund', 'Vankeev', 'svankeev2n@jalbum.net', '262-181-5062', 'Fleet Manager', '48');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (97, 'Beatriz', 'Knappett', 'bknappett2o@businessweek.com', '669-168-4154', 'Maintenance Staff', '78');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (98, 'Mitzi', 'Byrth', 'mbyrth2p@cargocollective.com', '701-759-0769', 'Maintenance Staff', '17');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (99, 'Fernanda', 'Vicioso', 'fvicioso2q@nih.gov', '763-127-0329', 'Fleet Manager', '28');
insert into Employee (employee_id, first_name, last_name, email, phone, role, location_id) values (100, 'Meyer', 'Chantrell', 'mchantrell2r@ft.com', '949-781-1914', 'Administrator', '91');
