create table Location (
	location_id INT,
	location_name VARCHAR(50),
	city VARCHAR(50),
	adress VARCHAR(50),
	zip_code VARCHAR(50)
);
insert into Location (location_id, location_name, city, adress, zip_code) values (1, 'Clarendon', 'Hushan', '71 Anhalt Place', '47');
insert into Location (location_id, location_name, city, adress, zip_code) values (2, 'Emmet', 'Luar', '59 Comanche Way', '9');
insert into Location (location_id, location_name, city, adress, zip_code) values (3, 'Delaware', 'Veghel', '7585 Valley Edge Way', '797');
insert into Location (location_id, location_name, city, adress, zip_code) values (4, 'Commercial', 'Inazawa', '4 Kenwood Street', '50570');
insert into Location (location_id, location_name, city, adress, zip_code) values (5, 'Namekagon', 'Albuquerque', '075 Heffernan Point', '4922');
insert into Location (location_id, location_name, city, adress, zip_code) values (6, 'American', 'Beltinci', '10 Starling Circle', '69');
insert into Location (location_id, location_name, city, adress, zip_code) values (7, 'Kim', 'Mont-Tremblant', '081 Eagan Trail', '573');
insert into Location (location_id, location_name, city, adress, zip_code) values (8, 'Grim', 'Bulacnin', '961 Delaware Place', '59601');
insert into Location (location_id, location_name, city, adress, zip_code) values (9, 'Harper', 'Yahotyn', '1 Walton Street', '02193');
insert into Location (location_id, location_name, city, adress, zip_code) values (10, 'Heath', 'Moutsamoudou', '7 Forest Place', '28');
insert into Location (location_id, location_name, city, adress, zip_code) values (11, 'Steensland', 'Gusong', '22239 Mockingbird Place', '771');
insert into Location (location_id, location_name, city, adress, zip_code) values (12, 'Kingsford', 'Khovd', '9025 Boyd Crossing', '65941');
insert into Location (location_id, location_name, city, adress, zip_code) values (13, 'Division', 'Saint-Paul', '15 Mitchell Crossing', '09');
insert into Location (location_id, location_name, city, adress, zip_code) values (14, 'Beilfuss', 'Várzea', '8 Prairie Rose Street', '5');
insert into Location (location_id, location_name, city, adress, zip_code) values (15, 'Mcbride', 'Temenggungan', '09390 Mockingbird Street', '65780');
insert into Location (location_id, location_name, city, adress, zip_code) values (16, 'Sachs', 'Candoso', '06 Prairieview Drive', '4');
insert into Location (location_id, location_name, city, adress, zip_code) values (17, 'Melvin', 'Gilowice', '741 Bonner Pass', '00197');
insert into Location (location_id, location_name, city, adress, zip_code) values (18, 'Superior', 'Letlhakeng', '3 Anniversary Terrace', '4');
insert into Location (location_id, location_name, city, adress, zip_code) values (19, 'Vermont', 'Zaindainxoi', '83135 Spaight Parkway', '28167');
insert into Location (location_id, location_name, city, adress, zip_code) values (20, 'School', 'Ýdra', '25 Nelson Crossing', '6367');
insert into Location (location_id, location_name, city, adress, zip_code) values (21, 'Clarendon', 'Disina', '3414 Schurz Alley', '73581');
insert into Location (location_id, location_name, city, adress, zip_code) values (22, 'Florence', 'Henggang', '3 Bay Trail', '49');
insert into Location (location_id, location_name, city, adress, zip_code) values (23, 'Lien', 'Obukhiv', '6 Schurz Junction', '463');
insert into Location (location_id, location_name, city, adress, zip_code) values (24, 'Dennis', 'Baoshan', '38264 Dayton Way', '9080');
insert into Location (location_id, location_name, city, adress, zip_code) values (25, 'Bashford', 'Glugur Tengah', '534 Rowland Park', '2846');
insert into Location (location_id, location_name, city, adress, zip_code) values (26, 'Onsgard', 'Vân Tùng', '09839 Pierstorff Drive', '1512');
insert into Location (location_id, location_name, city, adress, zip_code) values (27, 'Wayridge', 'Jintan', '0198 Village Drive', '23254');
insert into Location (location_id, location_name, city, adress, zip_code) values (28, 'Prairieview', 'Quinta da Torre', '282 Carioca Hill', '6366');
insert into Location (location_id, location_name, city, adress, zip_code) values (29, 'Marquette', 'Cravinhos', '736 Dovetail Center', '993');
insert into Location (location_id, location_name, city, adress, zip_code) values (30, 'Ryan', 'Shaliangzi', '45 Hazelcrest Place', '6360');
insert into Location (location_id, location_name, city, adress, zip_code) values (31, 'Warbler', 'Dolores', '23350 Mandrake Lane', '497');
insert into Location (location_id, location_name, city, adress, zip_code) values (32, 'Farwell', 'Tongqian', '62 Clyde Gallagher Circle', '9341');
insert into Location (location_id, location_name, city, adress, zip_code) values (33, 'Jana', 'Itaperuna', '95718 Kingsford Way', '27');
insert into Location (location_id, location_name, city, adress, zip_code) values (34, 'Talmadge', 'Tangnan', '76 Montana Junction', '3085');
insert into Location (location_id, location_name, city, adress, zip_code) values (35, 'Nelson', 'Bairro Assunção Piedade', '42 Schmedeman Drive', '276');
insert into Location (location_id, location_name, city, adress, zip_code) values (36, 'Drewry', 'Bakaran Kulon', '83 Forest Pass', '65');
insert into Location (location_id, location_name, city, adress, zip_code) values (37, 'Continental', 'Yuecheng', '9 Quincy Avenue', '6275');
insert into Location (location_id, location_name, city, adress, zip_code) values (38, 'Grim', 'Chekmagush', '05927 Tennyson Avenue', '3528');
insert into Location (location_id, location_name, city, adress, zip_code) values (39, 'Graceland', 'Kerep Wetan', '09558 Hazelcrest Trail', '67715');
insert into Location (location_id, location_name, city, adress, zip_code) values (40, 'Bobwhite', 'Asan-Maina Village', '24664 2nd Road', '6596');
insert into Location (location_id, location_name, city, adress, zip_code) values (41, 'Mandrake', 'Bulri', '97 Hauk Lane', '11112');
insert into Location (location_id, location_name, city, adress, zip_code) values (42, 'Paget', 'Yalagüina', '3401 Donald Street', '2');
insert into Location (location_id, location_name, city, adress, zip_code) values (43, 'Riverside', 'San Jerónimo', '02 Nelson Court', '94636');
insert into Location (location_id, location_name, city, adress, zip_code) values (44, 'Nova', 'Makanya', '3 Sommers Pass', '90');
insert into Location (location_id, location_name, city, adress, zip_code) values (45, 'Dawn', 'Aucallama', '0848 Harper Park', '86839');
insert into Location (location_id, location_name, city, adress, zip_code) values (46, 'Charing Cross', 'Moriguchi', '3557 Banding Park', '75');
insert into Location (location_id, location_name, city, adress, zip_code) values (47, 'Green', 'Arão', '9 Summit Terrace', '244');
insert into Location (location_id, location_name, city, adress, zip_code) values (48, 'Debra', 'Ježdovec', '9948 Montana Point', '9594');
insert into Location (location_id, location_name, city, adress, zip_code) values (49, 'Longview', 'Vittoriosa', '7912 Hagan Way', '7');
insert into Location (location_id, location_name, city, adress, zip_code) values (50, 'Algoma', 'Loma', '6 Nelson Plaza', '1');
insert into Location (location_id, location_name, city, adress, zip_code) values (51, 'Forest Run', 'Kulpin', '778 Caliangt Plaza', '2');
insert into Location (location_id, location_name, city, adress, zip_code) values (52, 'Golf Course', 'Plumbangan', '617 Namekagon Crossing', '67');
insert into Location (location_id, location_name, city, adress, zip_code) values (53, 'Burning Wood', 'Turośń Kościelna', '327 David Crossing', '034');
insert into Location (location_id, location_name, city, adress, zip_code) values (54, 'Hanover', 'Fulu', '739 Hayes Court', '78');
insert into Location (location_id, location_name, city, adress, zip_code) values (55, 'Jana', 'Tallkalakh', '7 Hollow Ridge Parkway', '3');
insert into Location (location_id, location_name, city, adress, zip_code) values (56, 'Welch', 'Basak', '91 Blaine Way', '83');
insert into Location (location_id, location_name, city, adress, zip_code) values (57, 'Manitowish', 'Longxing', '40 Marcy Center', '060');
insert into Location (location_id, location_name, city, adress, zip_code) values (58, 'Moland', 'Corona', '402 Briar Crest Parkway', '7289');
insert into Location (location_id, location_name, city, adress, zip_code) values (59, 'Dawn', 'Pigeiros', '65 Dapin Drive', '52618');
insert into Location (location_id, location_name, city, adress, zip_code) values (60, 'Bunker Hill', 'Temeke', '3 Village Alley', '6');
insert into Location (location_id, location_name, city, adress, zip_code) values (61, 'Bobwhite', 'Hamada', '41099 American Ash Pass', '47805');
insert into Location (location_id, location_name, city, adress, zip_code) values (62, 'Sommers', 'Rivière-du-Loup', '394 Fuller Street', '02291');
insert into Location (location_id, location_name, city, adress, zip_code) values (63, 'Derek', 'Dingshan', '5140 2nd Court', '17950');
insert into Location (location_id, location_name, city, adress, zip_code) values (64, 'Armistice', 'Xiadingjia', '467 Anniversary Place', '8385');
insert into Location (location_id, location_name, city, adress, zip_code) values (65, 'Mccormick', 'Jieshui', '96351 Ryan Center', '9485');
insert into Location (location_id, location_name, city, adress, zip_code) values (66, 'Sommers', 'Tongqiao', '70960 Forest Run Park', '5278');
insert into Location (location_id, location_name, city, adress, zip_code) values (67, 'Northport', 'Dajanrurung', '01638 Service Alley', '9');
insert into Location (location_id, location_name, city, adress, zip_code) values (68, 'Esker', 'Saijō', '8 Dwight Avenue', '46');
insert into Location (location_id, location_name, city, adress, zip_code) values (69, 'Cambridge', 'Kedungdoro', '9 Packers Lane', '8');
insert into Location (location_id, location_name, city, adress, zip_code) values (70, 'Dryden', 'Tieba', '2 Lyons Parkway', '371');
insert into Location (location_id, location_name, city, adress, zip_code) values (71, 'La Follette', 'Dongxi', '44 Oxford Court', '92924');
insert into Location (location_id, location_name, city, adress, zip_code) values (72, 'Cambridge', 'Pasarbaru', '50692 Portage Crossing', '9782');
insert into Location (location_id, location_name, city, adress, zip_code) values (73, 'Mesta', 'Yeniköy', '576 Bayside Street', '31');
insert into Location (location_id, location_name, city, adress, zip_code) values (74, 'Messerschmidt', 'Zorak', '89 Delladonna Way', '6076');
insert into Location (location_id, location_name, city, adress, zip_code) values (75, 'Talmadge', 'Feikeng', '673 Northview Junction', '39535');
insert into Location (location_id, location_name, city, adress, zip_code) values (76, 'Dawn', 'Amarillo', '4 Northwestern Trail', '2041');
insert into Location (location_id, location_name, city, adress, zip_code) values (77, 'Badeau', 'Pakis', '54534 Northview Place', '30');
insert into Location (location_id, location_name, city, adress, zip_code) values (78, 'Calypso', 'Soko', '2869 Bluejay Avenue', '85832');
insert into Location (location_id, location_name, city, adress, zip_code) values (79, 'Russell', 'Cezi', '1823 Kedzie Pass', '95866');
insert into Location (location_id, location_name, city, adress, zip_code) values (80, 'Melody', 'Orsk', '1278 Anthes Street', '0142');
insert into Location (location_id, location_name, city, adress, zip_code) values (81, 'Sheridan', 'Ta Phraya', '0 North Hill', '1');
insert into Location (location_id, location_name, city, adress, zip_code) values (82, 'Eagle Crest', 'Mubo', '81 Maple Wood Trail', '7498');
insert into Location (location_id, location_name, city, adress, zip_code) values (83, 'Cardinal', 'Liushun', '4684 Hoffman Parkway', '23425');
insert into Location (location_id, location_name, city, adress, zip_code) values (84, 'Eastwood', 'Dzaoudzi', '65267 Main Junction', '8939');
insert into Location (location_id, location_name, city, adress, zip_code) values (85, 'Thompson', 'Suncheon', '315 Myrtle Circle', '68122');
insert into Location (location_id, location_name, city, adress, zip_code) values (86, 'Colorado', 'Glad', '7 Lake View Lane', '7923');
insert into Location (location_id, location_name, city, adress, zip_code) values (87, 'Prairieview', 'Les Cèdres', '039 Hazelcrest Way', '0713');
insert into Location (location_id, location_name, city, adress, zip_code) values (88, 'Namekagon', 'Perepravnaya', '161 Merchant Street', '9150');
insert into Location (location_id, location_name, city, adress, zip_code) values (89, 'Miller', 'Dadamtu', '07 Stone Corner Street', '3574');
insert into Location (location_id, location_name, city, adress, zip_code) values (90, 'Hallows', 'Kolirerek', '14320 Muir Hill', '03');
insert into Location (location_id, location_name, city, adress, zip_code) values (91, 'Charing Cross', 'Nārang', '48 Bartillon Road', '19');
insert into Location (location_id, location_name, city, adress, zip_code) values (92, 'Green', 'Chropyně', '7 East Trail', '8515');
insert into Location (location_id, location_name, city, adress, zip_code) values (93, 'Arapahoe', 'Gantang', '3134 Cascade Circle', '118');
insert into Location (location_id, location_name, city, adress, zip_code) values (94, 'Dapin', 'Pasirpengarayan', '818 Larry Crossing', '25');
insert into Location (location_id, location_name, city, adress, zip_code) values (95, 'Glacier Hill', 'Yunxi', '89070 Declaration Way', '23');
insert into Location (location_id, location_name, city, adress, zip_code) values (96, 'Old Gate', 'Pameungpeuk', '299 Mifflin Avenue', '60095');
insert into Location (location_id, location_name, city, adress, zip_code) values (97, 'Ronald Regan', 'Jinli', '99 Daystar Trail', '149');
insert into Location (location_id, location_name, city, adress, zip_code) values (98, 'Shoshone', 'Kamigyō-ku', '5 Troy Parkway', '123');
insert into Location (location_id, location_name, city, adress, zip_code) values (99, 'Dwight', 'Jalingo', '6 Holy Cross Road', '91');
insert into Location (location_id, location_name, city, adress, zip_code) values (100, 'Paget', 'Guanyinsi', '10 Starling Place', '47');
