create table Payment (
	payment_id INT,
	amount VARCHAR(50),
	payment_method VARCHAR(18),
	rental_id VARCHAR(50)
);
insert into Payment (payment_id, amount, payment_method, rental_id) values (1, '12612', 'Bank Transfer', '10');
insert into Payment (payment_id, amount, payment_method, rental_id) values (2, '16546', 'Corporate  Billing', '55');
insert into Payment (payment_id, amount, payment_method, rental_id) values (3, '2123', 'Bank Transfer', '42');
insert into Payment (payment_id, amount, payment_method, rental_id) values (4, '6799', 'Bank Transfer', '56');
insert into Payment (payment_id, amount, payment_method, rental_id) values (5, '17315', 'Cash', '67');
insert into Payment (payment_id, amount, payment_method, rental_id) values (6, '2661', 'Credit', '47');
insert into Payment (payment_id, amount, payment_method, rental_id) values (7, '5560', 'Mobile Payment', '93');
insert into Payment (payment_id, amount, payment_method, rental_id) values (8, '6933', 'Corporate  Billing', '23');
insert into Payment (payment_id, amount, payment_method, rental_id) values (9, '10379', 'Bank Transfer', '53');
insert into Payment (payment_id, amount, payment_method, rental_id) values (10, '15698', 'Instalment', '38');
insert into Payment (payment_id, amount, payment_method, rental_id) values (11, '3099', 'Instalment', '44');
insert into Payment (payment_id, amount, payment_method, rental_id) values (12, '4280', 'Corporate  Billing', '100');
insert into Payment (payment_id, amount, payment_method, rental_id) values (13, '4179', 'Bank Transfer', '72');
insert into Payment (payment_id, amount, payment_method, rental_id) values (14, '17904', 'Credit', '76');
insert into Payment (payment_id, amount, payment_method, rental_id) values (15, '7816', 'Bank Transfer', '80');
insert into Payment (payment_id, amount, payment_method, rental_id) values (16, '15961', 'Credit', '99');
insert into Payment (payment_id, amount, payment_method, rental_id) values (17, '7244', 'Bank Transfer', '27');
insert into Payment (payment_id, amount, payment_method, rental_id) values (18, '12400', 'Corporate  Billing', '30');
insert into Payment (payment_id, amount, payment_method, rental_id) values (19, '3394', 'Instalment', '32');
insert into Payment (payment_id, amount, payment_method, rental_id) values (20, '13477', 'Bank Transfer', '66');
insert into Payment (payment_id, amount, payment_method, rental_id) values (21, '12455', 'Instalment', '90');
insert into Payment (payment_id, amount, payment_method, rental_id) values (22, '8654', 'Debit', '19');
insert into Payment (payment_id, amount, payment_method, rental_id) values (23, '12467', 'Debit', '64');
insert into Payment (payment_id, amount, payment_method, rental_id) values (24, '8957', 'Instalment', '68');
insert into Payment (payment_id, amount, payment_method, rental_id) values (25, '10331', 'Corporate  Billing', '20');
insert into Payment (payment_id, amount, payment_method, rental_id) values (26, '3164', 'Mobile Payment', '41');
insert into Payment (payment_id, amount, payment_method, rental_id) values (27, '10358', 'Cash', '45');
insert into Payment (payment_id, amount, payment_method, rental_id) values (28, '11115', 'Bank Transfer', '4');
insert into Payment (payment_id, amount, payment_method, rental_id) values (29, '16794', 'Instalment', '11');
insert into Payment (payment_id, amount, payment_method, rental_id) values (30, '7038', 'Cash', '48');
insert into Payment (payment_id, amount, payment_method, rental_id) values (31, '3347', 'Credit', '88');
insert into Payment (payment_id, amount, payment_method, rental_id) values (32, '2727', 'Cash', '1');
insert into Payment (payment_id, amount, payment_method, rental_id) values (33, '12169', 'Debit', '89');
insert into Payment (payment_id, amount, payment_method, rental_id) values (34, '9269', 'Instalment', '13');
insert into Payment (payment_id, amount, payment_method, rental_id) values (35, '12683', 'Debit', '87');
insert into Payment (payment_id, amount, payment_method, rental_id) values (36, '7932', 'Bank Transfer', '46');
insert into Payment (payment_id, amount, payment_method, rental_id) values (37, '13803', 'Mobile Payment', '82');
insert into Payment (payment_id, amount, payment_method, rental_id) values (38, '15933', 'Debit', '26');
insert into Payment (payment_id, amount, payment_method, rental_id) values (39, '6702', 'Bank Transfer', '35');
insert into Payment (payment_id, amount, payment_method, rental_id) values (40, '12380', 'Cash', '22');
insert into Payment (payment_id, amount, payment_method, rental_id) values (41, '10624', 'Instalment', '2');
insert into Payment (payment_id, amount, payment_method, rental_id) values (42, '6249', 'Debit', '61');
insert into Payment (payment_id, amount, payment_method, rental_id) values (43, '12059', 'Bank Transfer', '79');
insert into Payment (payment_id, amount, payment_method, rental_id) values (44, '6219', 'Bank Transfer', '29');
insert into Payment (payment_id, amount, payment_method, rental_id) values (45, '9636', 'Bank Transfer', '6');
insert into Payment (payment_id, amount, payment_method, rental_id) values (46, '15740', 'Instalment', '33');
insert into Payment (payment_id, amount, payment_method, rental_id) values (47, '8914', 'Cash', '17');
insert into Payment (payment_id, amount, payment_method, rental_id) values (48, '12435', 'Corporate  Billing', '59');
insert into Payment (payment_id, amount, payment_method, rental_id) values (49, '5854', 'Instalment', '75');
insert into Payment (payment_id, amount, payment_method, rental_id) values (50, '17544', 'Debit', '37');
insert into Payment (payment_id, amount, payment_method, rental_id) values (51, '7507', 'Credit', '39');
insert into Payment (payment_id, amount, payment_method, rental_id) values (52, '3626', 'Bank Transfer', '94');
insert into Payment (payment_id, amount, payment_method, rental_id) values (53, '4041', 'Credit', '92');
insert into Payment (payment_id, amount, payment_method, rental_id) values (54, '8237', 'Cash', '43');
insert into Payment (payment_id, amount, payment_method, rental_id) values (55, '11971', 'Credit', '63');
insert into Payment (payment_id, amount, payment_method, rental_id) values (56, '12434', 'Bank Transfer', '78');
insert into Payment (payment_id, amount, payment_method, rental_id) values (57, '12987', 'Mobile Payment', '84');
insert into Payment (payment_id, amount, payment_method, rental_id) values (58, '6692', 'Debit', '18');
insert into Payment (payment_id, amount, payment_method, rental_id) values (59, '5881', 'Bank Transfer', '74');
insert into Payment (payment_id, amount, payment_method, rental_id) values (60, '13890', 'Corporate  Billing', '52');
insert into Payment (payment_id, amount, payment_method, rental_id) values (61, '4239', 'Credit', '69');
insert into Payment (payment_id, amount, payment_method, rental_id) values (62, '3332', 'Mobile Payment', '16');
insert into Payment (payment_id, amount, payment_method, rental_id) values (63, '14280', 'Mobile Payment', '34');
insert into Payment (payment_id, amount, payment_method, rental_id) values (64, '16663', 'Instalment', '8');
insert into Payment (payment_id, amount, payment_method, rental_id) values (65, '3910', 'Bank Transfer', '40');
insert into Payment (payment_id, amount, payment_method, rental_id) values (66, '5122', 'Mobile Payment', '70');
insert into Payment (payment_id, amount, payment_method, rental_id) values (67, '12393', 'Mobile Payment', '5');
insert into Payment (payment_id, amount, payment_method, rental_id) values (68, '2710', 'Credit', '81');
insert into Payment (payment_id, amount, payment_method, rental_id) values (69, '9072', 'Debit', '36');
insert into Payment (payment_id, amount, payment_method, rental_id) values (70, '9637', 'Mobile Payment', '58');
insert into Payment (payment_id, amount, payment_method, rental_id) values (71, '17229', 'Mobile Payment', '15');
insert into Payment (payment_id, amount, payment_method, rental_id) values (72, '4985', 'Bank Transfer', '86');
insert into Payment (payment_id, amount, payment_method, rental_id) values (73, '8489', 'Instalment', '54');
insert into Payment (payment_id, amount, payment_method, rental_id) values (74, '15146', 'Bank Transfer', '98');
insert into Payment (payment_id, amount, payment_method, rental_id) values (75, '14121', 'Debit', '9');
insert into Payment (payment_id, amount, payment_method, rental_id) values (76, '3669', 'Mobile Payment', '3');
insert into Payment (payment_id, amount, payment_method, rental_id) values (77, '10807', 'Debit', '62');
insert into Payment (payment_id, amount, payment_method, rental_id) values (78, '6398', 'Bank Transfer', '28');
insert into Payment (payment_id, amount, payment_method, rental_id) values (79, '3645', 'Credit', '97');
insert into Payment (payment_id, amount, payment_method, rental_id) values (80, '3848', 'Instalment', '24');
insert into Payment (payment_id, amount, payment_method, rental_id) values (81, '13581', 'Cash', '31');
insert into Payment (payment_id, amount, payment_method, rental_id) values (82, '2875', 'Debit', '14');
insert into Payment (payment_id, amount, payment_method, rental_id) values (83, '7761', 'Debit', '12');
insert into Payment (payment_id, amount, payment_method, rental_id) values (84, '12032', 'Debit', '57');
insert into Payment (payment_id, amount, payment_method, rental_id) values (85, '6315', 'Corporate  Billing', '21');
insert into Payment (payment_id, amount, payment_method, rental_id) values (86, '2880', 'Mobile Payment', '95');
insert into Payment (payment_id, amount, payment_method, rental_id) values (87, '12752', 'Instalment', '65');
insert into Payment (payment_id, amount, payment_method, rental_id) values (88, '13464', 'Debit', '96');
insert into Payment (payment_id, amount, payment_method, rental_id) values (89, '14228', 'Instalment', '73');
insert into Payment (payment_id, amount, payment_method, rental_id) values (90, '6709', 'Credit', '83');
insert into Payment (payment_id, amount, payment_method, rental_id) values (91, '3480', 'Cash', '71');
insert into Payment (payment_id, amount, payment_method, rental_id) values (92, '15968', 'Debit', '50');
insert into Payment (payment_id, amount, payment_method, rental_id) values (93, '13286', 'Instalment', '91');
insert into Payment (payment_id, amount, payment_method, rental_id) values (94, '2804', 'Credit', '85');
insert into Payment (payment_id, amount, payment_method, rental_id) values (95, '2576', 'Debit', '51');
insert into Payment (payment_id, amount, payment_method, rental_id) values (96, '3911', 'Debit', '7');
insert into Payment (payment_id, amount, payment_method, rental_id) values (97, '6315', 'Debit', '49');
insert into Payment (payment_id, amount, payment_method, rental_id) values (98, '2875', 'Debit', '14');
insert into Payment (payment_id, amount, payment_method, rental_id) values (99, '12987', 'Corporate  Billing', '84');
insert into Payment (payment_id, amount, payment_method, rental_id) values (100, '3911', 'Credit', '7');
